//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NETEntities1 : DbContext
    {
        public NETEntities1()
            : base("name=NETEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comments> comments { get; set; }
        public DbSet<group> group { get; set; }
        public DbSet<post> post { get; set; }
        public DbSet<star> star { get; set; }
        public DbSet<user> user { get; set; }
    }
}
