//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public post()
        {
            this.star = new HashSet<star>();
        }
    
        public int postId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> groupId { get; set; }
        public byte[] content { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string title { get; set; }
        public Nullable<int> starNum { get; set; }
    
        public virtual group group { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<star> star { get; set; }
    }
}
