//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.comments = new HashSet<comments>();
            this.post = new HashSet<post>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string avatar { get; set; }
        public string signature { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<comments> comments { get; set; }
        public virtual ICollection<post> post { get; set; }
    }
}
